# Generated by Django 5.1.6 on 2025-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_discount_order_final_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="point_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="points_redeemed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
