# Generated by Django 5.1.6 on 2025-04-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0003_alter_promocode_code"),
        ("orders", "0004_order_point_discount_order_points_redeemed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="used_discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discounts.discount",
            ),
        ),
    ]
