# Generated by Django 5.1.6 on 2025-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_category_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("printer", "Printer"),
                    ("ink", "Ink"),
                    ("heatpress", "Heatpress"),
                    ("accessory", "Accessory"),
                ],
                max_length=100,
            ),
        ),
    ]
