# Generated by Django 5.1.6 on 2025-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_add_sale_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_on_sale",
            field=models.BooleanField(default=False),
        ),
    ]
