# Generated by Django 5.1.6 on 2025-04-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0002_promocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
