# Generated by Django 5.1.6 on 2025-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
